final List<String> quantity = <String>[
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
  '1kg',
  '3Kg',
  '10kg',
  '1kg',
  '1 Kg',
  '3Kg',
  '10kg',
  '1kg',
];
final List<String> notes = <String>[
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
  'half kg semi ripe',
  'medium to large head',
  'Heads should be firm ',
  'jazz,GrannySmith,Jonagold and Fuji',
];
final List<String> names = <String>[
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
  'Tomatoes ',
  'Cauliflower ',
  'Brocolli ',
  'Apples ',
];
